### ISSUE TITLE
In iframe hybridauth getting exception

### ISSUE THREAD

**Issue by kailasb** [hybridauth/hybridauth#1259]
I've integrate the hybirdauth in my project it's working fine but when I tried to login in another project using iframe it's not working.

Version: 2.15.1

Getting below error:
FATAL ERROR - Loader failed to load component (view) hybridauth/router

{"msg":"Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly.","file":"\/var\/www\/html\/plugins\/hybridauth\/hybridauth\/Hybrid\/Endpoint.php","line":217,"trace":"#0 \/var\/www\/html\/plugins\/hybridauth\/hybridauth\/Hybrid\/Endpoint.php(117): Hybrid_Endpoint->authInit()\n#1 \/var\/www\/html\/plugins\/hybridauth\/hybridauth\/Hybrid\/Endpoint.php(51): Hybrid_Endpoint->processAuthStart()\n#2 \/var\/www\/html\/plugins\/hybridauth\/hybridauth\/Hybrid\/Endpoint.php(72): Hybrid_Endpoint->__construct(Array)\n#3 \/var\/www\/html\/plugins\/hybridauth\/hybridauth\/index.php(15): Hybrid_Endpoint::process()\n#4 \/var\/www\/html\/views\/hybridauth\/router.php(43): require_once('\/var\/www\/h...')\n#5 \/var\/www\/html\/libraries\/loader.php(106): require('\/var\/www\/h...')\n#6 \/var\/www\/html\/libraries\/router.php(117): load_view('hybridauth\/rout...')\n#7 \/var\/www\/html\/index.php(29): route('hybridauth')\n#8 {main}"}

can you guide what's wrong in that

**Comment by ApacheEx** [comment]
most probably the session was lost. That's why you receive access denied.

not sure if it should be handled by this library, but if you find out what is the reason...feel free to submit the PR.
