### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by ojhaujjwal** [hybridauth/hybridauth#200]
This library works great if the user grants permission. But, if, he refuses, I get this error:

```
Serialization of 'Closure' is not allowed
```

Stack Trace:

```
#0 D:\webdocuments\cm\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Storage.php(0): serialize()
#1 D:\webdocuments\cm\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Error.php(26): Hybrid_Storage->set('hauth_session.e...', Object(Exception))
#2 D:\webdocuments\cm\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Endpoint.php(179): Hybrid_Error::setError('Authentication ...', 5, '#0 D:\webdocume...', Object(Exception))
#3 D:\webdocuments\cm\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Endpoint.php(56): Hybrid_Endpoint::processAuthDone()
#4 D:\webdocuments\cm\vendor\socalnick\scn-social-auth\src\ScnSocialAuth\Controller\HybridAuthController.php(10): Hybrid_Endpoint::process()
#5 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(83): ScnSocialAuth\Controller\HybridAuthController->indexAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 D:\webdocuments\cm\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 D:\webdocuments\cm\index.php(23): Zend\Mvc\Application->run()
#16 {main}
```

**Comment by rudy1976s** [comment]
Is there any news about this issue? I am using the hybridAuth in a cakePHP 2.6 project, deployed in two different mamp pro containers : in one it works fine without raising errors while the other has never worked out. Same php 5.5.2.3 on both containers.

**Comment by karthikeyan-manivasagam** [comment]
Im using phalcon linkedin not working i fixed by this steps 

http://monkpal.com/exception-serialization-closure-not-allowed-hybridauth-linkedin-phalcon
