### ISSUE TITLE
Odnoklassniki provider error... when handling error

### ISSUE THREAD

**Issue by FractalizeR** [hybridauth/hybridauth#346]
Sometimes the following code snippet in the `Hybrid_Providers_Odnoklassniki::authodnoklass`

```
if( ! $response || ! isset( $response->access_token ) ){
    throw new Exception( "The Authorization Service has return: " . $response->error );
}
```

produces the following error:

```
[2014-11-11 04:04:19] production.ERROR: exception 'Exception' with message 'User profile request failed! Odnoklassniki returned an error: exception 'ErrorException' with message 'Undefined property: stdClass::$error' in /var/www/auth.forumhouse.ru/vendor/hybridauth/hybridauth/additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php:95
Stack trace:
#0 /var/www/auth.forumhouse.ru/vendor/hybridauth/hybridauth/additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php(95): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/auth.f...', 95, Array)
#1 /var/www/auth.forumhouse.ru/vendor/hybridauth/hybridauth/additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php(128): Hybrid_Providers_Odnoklassniki->authodnoklass('xxxxxxxxxxx...')
#2 /var/www/auth.forumhouse.ru/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php(175): Hybrid_Providers_Odnoklassniki->loginFinish()
#3 /var/www/auth.forumhouse.ru/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php(56): Hybrid_Endpoint::processAuthDone()
```

I guess some special cases exist when curl result doesn't contain anything like 'error' and this should be handled also.

**Comment by ApacheEx** [comment]
closed as there is no activity over a year
