### ISSUE TITLE
Authentication failed. The user has canceled the authentication or the provider refused the connection. In Facebook

### ISSUE THREAD

**Issue by githubitsme** [hybridauth/hybridauth#620]
This error occurs when I am authenticating with Facebook.Please help me to solve this I've Hardly spent 3 hrs to fix it But  I can't.

```
Authentication failed. The user has canceled the authentication or the provider refused the connection.

Original error message: Authentication failed! Facebook returned an invalid user id.
Trace

#0 C:\wamp\www\edit\hybridauth\Hybrid\Auth.php(55): Hybrid_Auth::initialize(Array)
#1 C:\wamp\www\edit\login-with.php(11): Hybrid_Auth->__construct(Array)
#2 {main}
```
Config.php
```
<?php
/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------
$config =array(
		"base_url" => "http://localhost/edit/hybridauth/index.php", 
		"providers" => array ( 

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "XXXXXXXXXXXX", "secret" => "XXXXXXXX" ), 
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "My id", "secret" => "My secret" ), 
			    "scope"   => "email, user_about_me, user_birthday, user_hometown",

			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "XXXXXXXX", "secret" => "XXXXXXX" ) 
			),
		),
		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,
		"debug_file" => "",
	);

```

Login-with.php

```
<?php
        session_start();
        include('config.php');
        include('hybridauth/Hybrid/Auth.php');
        if(isset($_GET['provider']))
        {
        	$provider = $_GET['provider'];
        	
        	try{
        	
        	$hybridauth = new Hybrid_Auth( $config );
        	
        	$authProvider = $hybridauth->authenticate($provider);

	        $user_profile = $authProvider->getUserProfile();
	        
			if($user_profile && isset($user_profile->identifier))
	        {
	        	echo "<b>Name</b> :".$user_profile->displayName."<br>";
	        	echo "<b>Profile URL</b> :".$user_profile->profileURL."<br>";
	        	echo "<b>Image</b> :".$user_profile->photoURL."<br> ";
	        	echo "<img src='".$user_profile->photoURL."'/><br>";
	        	echo "<b>Email</b> :".$user_profile->email."<br>";	        		        		        	
	        	echo "<br> <a href='logout.php'>Logout</a>";
	        }	        

			}
			catch( Exception $e )
			{ 
			
				 switch( $e->getCode() )
				 {
                        case 0 : echo "Unspecified error."; break;
                        case 1 : echo "Hybridauth configuration error."; break;
                        case 2 : echo "Provider not properly configured."; break;
                        case 3 : echo "Unknown or disabled provider."; break;
                        case 4 : echo "Missing provider application credentials."; break;
                        case 5 : echo "Authentication failed. "
                                         . "The user has canceled the authentication or the provider refused the connection.";
                                 break;
                        case 6 : echo "User profile request failed. Most likely the user is not connected "
                                         . "to the provider and he should to authenticate again.";
                                 $twitter->logout();
                                 break;
                        case 7 : echo "User not connected to the provider.";
                                 $twitter->logout();
                                 break;
                        case 8 : echo "Provider does not support this feature."; break;
                }

                // well, basically your should not display this to the end user, just give him a hint and move on..
                echo "<br /><br /><b>Original error message:</b> " . $e->getMessage();

                echo "<hr /><h3>Trace</h3> <pre>" . $e->getTraceAsString() . "</pre>";

			}
        
        }
?>
```

**Comment by g4b1nagy** [comment]
+1 on having this issue. I've tried with both an old Facebook app and with a newly created one.

**Comment by githubitsme** [comment]
@g4b1nagy How to solve this issue

**Comment by g4b1nagy** [comment]
I don't know yet. I've spent a few hours trying to debug this, and the culprit seems to be `getUserFromAvailableData` method here => https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/thirdparty/Facebook/base_facebook.php#L581 which returns 0 instead of a valid user id.

The `getUserFromAccessToken` method here => https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/thirdparty/Facebook/base_facebook.php#L765 also seems to be doing something wrong, because it's issuing an Open Graph request without supplying an access token.

I will let you know if I manage to make some progress with this.

**Comment by sahilsharmafrank** [comment]
It's not an issue, it occurs when a user cancels the access to profile. If you don't allow it occurs that means you should not login this user to your app as he has not granted you the access.

**Comment by g4b1nagy** [comment]
@githubitsme I started from scratch today i.e. new Facebook app and clean code and I'm not able to reproduce it anymore. Weird.

**Comment by githubitsme** [comment]
Just forget about hybrid auth And go for normal working scripts.This link will help you
[](www.codexworld.com/login-with-facebook-using-php/)

**Comment by opure** [comment]
@g4b1nagy Hello,Did you solve this problem,I also have this problem .

**Comment by g4b1nagy** [comment]
@opure Unfortunately, I have no idea what I was doing wrong. I just threw out the old code, started from scratch and then it worked...

**Comment by opure** [comment]
@g4b1nagy Thank you still,I'll go and look for problems.
